#!/bin/sh
wpa_file="/boot/wpa_supplicant.conf"
wlan0_file="/boot/wlan0.network"

COPY_WPA_CONFIG() {
    mv "$wpa_file" /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
}

COPY_WLAN_CONFIG() {
    mv "$wlan0_file" /etc/systemd/network/wlan0.network
}

WRITE_DEFAULT_WLAN_CONFIG() {
        cat << EOF > /etc/systemd/network/wlan0.network
[Match]
Name=wlan0

[Network]
DHCP=yes
EOF
}

ENABLE_NETWORKING() {
    systemctl enable --now wpa_supplicant@wlan0.service
}

if [ -f "$wpa_file" ]; then
    COPY_WPA_CONFIG
fi

if [ -f "$wlan0_file" ]; then
    COPY_WLAN_CONFIG
else
    WRITE_DEFAULT_WLAN_CONFIG
fi

ENABLE_NETWORKING
