#!/bin/sh
WPA_FILE="/boot/wpa_supplicant.conf"
WPA_DEST="/etc/wpa_supplicant/wpa_supplicant-wlan0.conf"
WLAN0_FILE="/boot/wlan0.network"
WLAN0_DEST="/etc/systemd/network/wlan0.network"

copy_wpa_config() {
    echo "Moving ${WPA_FILE} to ${WPA_DEST}"
    mv "${WPA_FILE}" "${WPA_DEST}"
}

copy_wlan_config() {
    echo "Moving ${WLAN0_FILE} to ${WLAN0_DEST}"
    mv "${WLAN0_FILE}" "${WLAN0_DEST}"
}

write_default_wlan_config() {
    echo "Writing default ${WLAN0_DEST}"
    cat << EOF > "${WLAN0_DEST}"
[Match]
Name=wlan0

[Network]
DHCP=yes
EOF
}

while [ "$(systemctl is-failed bootrunner.service)" != "inactive" ]; do
    echo "get_wpa waiting for bootrunner to finish"
    sleep 1
done
echo "get_wpa done waiting for bootrunner to finish"

if [ -f "$WPA_FILE" ]; then
    copy_wpa_config
fi

if [ ! -f "$WLAN0_FILE" ] && [ ! -f "$WLAN0_DEST" ]; then
    write_default_wlan_config
elif [ -f "${WLAN0_FILE}" ]; then
    copy_wlan_config
fi

echo "Enabling wpa_supplicant@wlan0.service"
systemctl enable --now wpa_supplicant@wlan0.service
systemctl enable systemd-networkd.service
systemctl restart systemd-networkd.service
